#!/bin/bash

#пулимся с ветки *
git pull origin "$*"

#обновляем миграции и конфиги
docker-compose exec app php artisan migrate
docker-compose exec app php artisan optimize
docker-compose exec app composer dump-autoload

#перезапускаем джобы
docker-compose up -d --no-deps --build queue-default
docker-compose up -d --no-deps --build queue-products-shaping
docker-compose up -d --no-deps --build queue-update-clicks
docker-compose up -d --no-deps --build queue-files
docker-compose up -d --no-deps --build queue-email
